### ISSUE TITLE
QR code in apple wallet is too small on ios 14

### ISSUE THREAD

**Issue by yonigold1** [billylo1/covidpass#42]
I'm on ios 14 and i created the vaccine pass however the QR code is extremely small and trying to scan it with the verifier app doesn't work unless the qr code is bigger. Can you please make it a bit more bigger?
![image](https://user-images.githubusercontent.com/34217684/137580420-1d02a4ad-f084-458b-9640-86d379ee2fdc.jpeg)

**Comment by yonigold1** [comment]
I tried adding it on my iPhone 7 and it just seems to be a sizing bug for the bigger iPhones (my main iPhone is a 12 Pro Max)

**Comment by straxus** [comment]
Unfortunately we have no control over how Apple Wallet displays the QR code we give it - and in particular, Apple Wallet on iOS 13 and 14 does not draw these QR codes correctly. This is a known Apple bug and it seems unlikely at this point that they will fix it - we suggest using a Photo pass if you can't update to iOS 15 or later.

We updated our app to no longer allow importing Apple Wallet cards if you're on iOS < 15 because of this.

I also highly suggest you redact or delete your image above @yonigold1 - the image IS scannable, and it reveals your name and birthdate.
